name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:${{matrix.channel}}

    strategy:
      matrix:
        channel:
          - latest
          - stable

    steps:
      - uses: actions/checkout@v2

      - run: flutter pub global activate melos

      - name: Installing dependencies
        run: melos bootstrap
      
      - name: Check format
        run: melos exec -- dart format --set-exit-if-changed .

      - name: Analyze project
        run: melos exec -- dart analyze .

      - name: Test
        run: melos exec --  ../../scripts/auto_test.sh
